import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "-apple-system", "system-ui", "Segoe UI", "Helvetica", "sans-serif"],
      },
      colors: {
        primary: "#5645d4",
        "primary-pressed": "#4534b3",
        "primary-deep": "#3a2a99",
        "brand-navy": "#0a1530",
        "brand-navy-deep": "#070f24",
        "brand-navy-mid": "#1a2a52",
        "brand-hero": "#0a0e1a",
        "link-blue": "#0075de",
        "brand-orange": "#dd5b00",
        "brand-orange-deep": "#793400",
        "brand-pink": "#ff64c8",
        "brand-pink-deep": "#a02e6d",
        "brand-purple": "#7b3ff2",
        "brand-purple-300": "#d6b6f6",
        "brand-purple-800": "#391c57",
        "brand-teal": "#2a9d99",
        "brand-green": "#1aae39",
        "brand-yellow": "#f5d75e",
        "brand-brown": "#523410",
        "canvas": "#ffffff",
        "surface": "#f6f5f4",
        "surface-soft": "#fafaf9",
        "hairline": "#e5e3df",
        "hairline-soft": "#ede9e4",
        "hairline-strong": "#c8c4be",
        "ink-deep": "#000000",
        "ink": "#1a1a1a",
        "charcoal": "#37352f",
        "slate-t": "#5d5b54",
        "steel": "#787671",
        "stone": "#a4a097",
        "muted": "#bbb8b1",
        "on-dark": "#ffffff",
        "on-dark-muted": "#a4a097",
        "tint-peach": "#ffe8d4",
        "tint-rose": "#fde0ec",
        "tint-mint": "#d9f3e1",
        "tint-lavender": "#e6e0f5",
        "tint-sky": "#dcecfa",
        "tint-yellow": "#fef7d6",
        "tint-yellow-bold": "#f9e79f",
        "tint-cream": "#f8f5e8",
        "tint-gray": "#f0eeec",
      },
    },
  },
  plugins: [],
};

export default config;
